id: AC3825062
title: In Praise of the Three Jewels
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:26:52.747717
  last_modified_at: 2022-03-01 02:26:52.747725
